name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-24.04
    steps:
    - uses: googleapis/release-please-action@v4
      id: release
      with:
        token: ${{secrets.GH_OPENUI5BOT}}
